name: "Test Build Project"

on: push

jobs:
  build:
    name: "Build Thing"
    runs-on: ubuntu-latest # may need to switch to windows-latest

    continue-on-error: true

    steps:
      - name: "checkout"
        uses: actions/checkout@v2

      - name: "setup java"
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk

      # - uses: nttld/setup-ndk@v1
      #   with:
      #     ndk-version: r21d
      # - run: ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk

      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}

      - name: "change permission"
        run: "sudo chmod a+rwx ./gradlew"

      - name: "build"
        id: build
        run: "sudo ./gradlew assembleDebug"

    outputs:
      status: "${{ steps.buid.outcome }}"

  sendMessage:
    name: "Send Message"
    runs-on: ubuntu-18.04

    needs: build

    steps:
      - name: "SendLog"
        env:
          WEBHOOK_ID: ${{ secrets.WEBHOOK_ID }}
          WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_TOKEN }}
          MSG: '{
            "title": "${{ github.event.pusher.name }} Pushed",
            "description": "In repository: ${{ github.event.repository.html_url }}",
            "fields": [
              {"name": "Status", "value": "${{ needs.build.outputs.status }}"}
            ]
          }'
        run: 'curl -H "Content-Type: application/json" -d "{\"embeds\": [$MSG]}" -X POST https://discord.com/api/webhooks/$WEBHOOK_ID/$WEBHOOK_TOKEN'